[[main]]
name = "Archive"
pageRef = "posts"
identifier = "fEy6WnmYT9"
weight = 9999

[[main]]
name = "Topics"
pageRef = "tags"
identifier = "Uo0wgqInZq"
weight = 9999

[[main]]
name = "About"
pageRef = "about"
identifier = "LLVfsqAqP3"
weight = 9999

[[footer]]
none = "none"
